server:
  port: 8085
  context-path: /springboot_demo2
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3036/baizhi
    username: root
    password: 123456
  mvc:
    view:
      suffix: /
      prefix: .jsp
  http:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  type-aliases-package: com.baizhi.entity